/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as talentFactorySol from "./TalentFactory.sol";
export type { talentFactorySol };
import type * as talentTokenSol from "./TalentToken.sol";
export type { talentTokenSol };
import type * as staking from "./staking";
export type { staking };
import type * as test from "./test";
export type { test };
import type * as tokens from "./tokens";
export type { tokens };
export type { CommunityMember } from "./CommunityMember";
export type { CommunityUser } from "./CommunityUser";
export type { Staking } from "./Staking";
export type { StakingMigration } from "./StakingMigration";
export type { TalentFactoryV2 } from "./TalentFactoryV2";
export type { TalentProtocol } from "./TalentProtocol";
