/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC1363ReceiverUpgradeable } from "./IERC1363ReceiverUpgradeable";
export type { IERC1363SpenderUpgradeable } from "./IERC1363SpenderUpgradeable";
export type { IERC1363Upgradeable } from "./IERC1363Upgradeable";
