/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ITalentFactory__factory } from "./ITalentFactory__factory";
export { TalentFactory__factory } from "./TalentFactory__factory";
