/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20MockSol from "./ERC20Mock.sol";
export type { erc20MockSol };
export type { InterfaceIDs } from "./InterfaceIDs";
export type { StakingV2 } from "./StakingV2";
export type { TalentProtocolV2 } from "./TalentProtocolV2";
export type { TalentTokenV2 } from "./TalentTokenV2";
export type { TestRewardCalculator } from "./TestRewardCalculator";
export type { TestStableThenToken } from "./TestStableThenToken";
