/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface InterfaceIDsInterface extends utils.Interface {
  functions: {
    "accessControl()": FunctionFragment;
    "accessControlEnumerable()": FunctionFragment;
    "erc1363()": FunctionFragment;
    "erc165()": FunctionFragment;
    "erc20()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "accessControl"
      | "accessControlEnumerable"
      | "erc1363"
      | "erc165"
      | "erc20"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "accessControl",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "accessControlEnumerable",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "erc1363", values?: undefined): string;
  encodeFunctionData(functionFragment: "erc165", values?: undefined): string;
  encodeFunctionData(functionFragment: "erc20", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "accessControl",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "accessControlEnumerable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "erc1363", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "erc165", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "erc20", data: BytesLike): Result;

  events: {};
}

export interface InterfaceIDs extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: InterfaceIDsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    accessControl(overrides?: CallOverrides): Promise<[string]>;

    accessControlEnumerable(overrides?: CallOverrides): Promise<[string]>;

    erc1363(overrides?: CallOverrides): Promise<[string]>;

    erc165(overrides?: CallOverrides): Promise<[string]>;

    erc20(overrides?: CallOverrides): Promise<[string]>;
  };

  accessControl(overrides?: CallOverrides): Promise<string>;

  accessControlEnumerable(overrides?: CallOverrides): Promise<string>;

  erc1363(overrides?: CallOverrides): Promise<string>;

  erc165(overrides?: CallOverrides): Promise<string>;

  erc20(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    accessControl(overrides?: CallOverrides): Promise<string>;

    accessControlEnumerable(overrides?: CallOverrides): Promise<string>;

    erc1363(overrides?: CallOverrides): Promise<string>;

    erc165(overrides?: CallOverrides): Promise<string>;

    erc20(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    accessControl(overrides?: CallOverrides): Promise<BigNumber>;

    accessControlEnumerable(overrides?: CallOverrides): Promise<BigNumber>;

    erc1363(overrides?: CallOverrides): Promise<BigNumber>;

    erc165(overrides?: CallOverrides): Promise<BigNumber>;

    erc20(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    accessControl(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    accessControlEnumerable(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    erc1363(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    erc165(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    erc20(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
