/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC1363__factory } from "./ERC1363__factory";
export { ERC1363Upgradeable__factory } from "./ERC1363Upgradeable__factory";
