/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20Mock } from "./ERC20Mock";
export type { ERC20MockWithoutErc165 } from "./ERC20MockWithoutErc165";
export type { USDTMock } from "./USDTMock";
