pragma solidity ^0.8.7;

enum TIERS {
    UNDEFINED,
    PUBLIC_STAGE,
    USER,
    PARTNER,
    TOKEN_HOLDER,
    TALENT_HOUSE,
    CONTRIBUTOR,
    INVESTOR,
    ACTIVE_CONTRIBUTOR,
    CORE_TEAM
}