/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ITalentToken__factory } from "./ITalentToken__factory";
export { TalentToken__factory } from "./TalentToken__factory";
