/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as talentFactorySol from "./TalentFactory.sol";
export * as talentTokenSol from "./TalentToken.sol";
export * as staking from "./staking";
export * as test from "./test";
export * as tokens from "./tokens";
export { CommunityMember__factory } from "./CommunityMember__factory";
export { CommunityUser__factory } from "./CommunityUser__factory";
export { Staking__factory } from "./Staking__factory";
export { StakingMigration__factory } from "./StakingMigration__factory";
export { TalentFactoryV2__factory } from "./TalentFactoryV2__factory";
export { TalentProtocol__factory } from "./TalentProtocol__factory";
