/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as draftIerc1822Sol from "./draft-IERC1822.sol";
export type { draftIerc1822Sol };
export type { IERC1363 } from "./IERC1363";
export type { IERC1363Receiver } from "./IERC1363Receiver";
export type { IERC1363Spender } from "./IERC1363Spender";
