/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ITalentFactory } from "./ITalentFactory";
export type { TalentFactory } from "./TalentFactory";
