/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc20MockSol from "./ERC20Mock.sol";
export { InterfaceIDs__factory } from "./InterfaceIDs__factory";
export { StakingV2__factory } from "./StakingV2__factory";
export { TalentProtocolV2__factory } from "./TalentProtocolV2__factory";
export { TalentTokenV2__factory } from "./TalentTokenV2__factory";
export { TestRewardCalculator__factory } from "./TestRewardCalculator__factory";
export { TestStableThenToken__factory } from "./TestStableThenToken__factory";
