/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as rewardCalculatorSol from "./RewardCalculator.sol";
export type { rewardCalculatorSol };
export type { StableThenToken } from "./StableThenToken";
